services:
    authentication-service:
        build:
            context: .
            dockerfile: ./AuthenticationService/AuthenticationService.Server/Dockerfile
        container_name: manager-authentication-service
        ports:
            - "${AUTHENTICATION_SERVICE_PORT}:8080"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        env_file:
            - ./AuthenticationService/AuthenticationService.Server/.env
        networks:
            - my-network

networks:
    my-network:
        driver: bridge
        ipam:
            config:
                - subnet: "172.20.0.0/16"