services:
    authentication-service:
        build:
            context: .
            dockerfile: ./AuthenticationService/AuthenticationService.Server/Dockerfile
        container_name: manager-authentication-service
        ports:
            - "8081:8080"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://0.0.0.0:8080
        env_file:
            ./AuthenticationService/AuthenticationService.Server/.env
        networks:
            - my-network
        extra_hosts:
            - "host.docker.internal:host-gateway"


networks:
    my-network:
        driver: bridge
        ipam:
            config:
                - subnet: "172.20.0.0/16"