services:
    authentication-service:
        build:
            context: .
            dockerfile: ./AuthenticationService/AuthenticationService.Server/Dockerfile
        container_name: manager-authentication-service
        ports:
            - "${AUTHENTICATION_SERVICE_PORT}:8080"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        env_file:
            -   path: ./AuthenticationService/AuthenticationService.Server/.env
                required: false
        networks:
            - my-network

    work-service:
        build:
            context: .
            dockerfile: ./WorkService/WorkService.Server/Dockerfile
        container_name: manager-work-service
        ports:
            - "${WORK_SERVICE_PORT}:8080"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        env_file:
            -   path: ./WorkService/WorkService.Server/.env
                required: false
        networks:
            - my-network

networks:
    my-network:
        driver: bridge
        ipam:
            config:
                -   subnet: "172.20.0.0/16"