name: Project Tests

on:
  push:
    branches: [ main, api_integrational_tests ]
  workflow_dispatch:

jobs:
  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Set up Docker Compose
        run: |
          sudo mkdir -p /usr/local/lib/docker/cli-plugins
          sudo curl -SL "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64" -o /usr/local/lib/docker/cli-plugins/docker-compose
          sudo chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
          docker compose version

      - name: Grant Docker permissions
        run: sudo chmod 666 /var/run/docker.sock

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Build docker image
        run: docker-compose build

      - name: Run Integration Tests
        run: dotnet test Manager.sln --no-build --filter "TestCategory=IntegrationTests" --logger "trx"

      - name: Publish Test Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Integration Tests
          path: "**/*.trx"
          reporter: dotnet-trx