name: Project Tests

on:
  push:
    branches: [ main, api_integrational_tests ]
  workflow_dispatch:

jobs:
  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Grant Docker permissions
        run: sudo chmod 666 /var/run/docker.sock

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Run docker compose
        uses: hoverkraft-tech/compose-action@b716db5b717cb9b81e391fe638e5aceaa2299e43

      - name: Docker compose build
        run: docker compose build

      - name: Run Integration Tests
        run: dotnet test Manager.sln --no-build --filter "TestCategory=IntegrationTests" --logger "trx"

      - name: Publish Test Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Integration Tests
          path: "**/*.trx"
          reporter: dotnet-trx