name: Project Tests

on:
    push:
        branches: [ main ]
    workflow_dispatch:

jobs:
    unit-tests:
        name: Unit Tests
        runs-on: ubuntu-latest
        permissions:
            checks: write
            pull-requests: write

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Setup .NET 9
                uses: actions/setup-dotnet@v4
                with:
                    dotnet-version: '9.0.x'

            -   name: Restore dependencies
                run: dotnet restore

            -   name: Build
                run: dotnet build --no-restore

            -   name: Run Tests
                run: dotnet test --no-build --filter "TestCategory=UnitTests" --logger "trx"

            -   name: Publish Test Results
                uses: dorny/test-reporter@v1
                if: always()
                with:
                    name: Unit Tests Report
                    path: "**/*.trx"
                    reporter: dotnet-trx

    integration-tests:
        name: Integration Tests
        runs-on: ubuntu-latest
        permissions:
            checks: write
            pull-requests: write

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Setup .NET 9
                uses: actions/setup-dotnet@v4
                with:
                    dotnet-version: '9.0.x'

            -   name: Grant Docker permissions
                run: sudo chmod 666 /var/run/docker.sock

            -   name: Restore dependencies
                run: dotnet restore

            -   name: Build
                run: dotnet build --no-restore

            -   name: Run docker compose
                uses: hoverkraft-tech/compose-action@b716db5b717cb9b81e391fe638e5aceaa2299e43

            -   name: Docker compose build
                run: docker compose build

            -   name: Run Tests
                run: dotnet test --no-build --filter "TestCategory=IntegrationTests" --logger "trx"

            -   name: Publish Test Results
                uses: dorny/test-reporter@v1
                if: always()
                with:
                    name: Integration Tests Report
                    path: "**/*.trx"
                    reporter: dotnet-trx